#
# Makefile
#

CIRCLE_STDLIB_DIR = ../circle-stdlib
CMSIS_DIR = ../CMSIS_5/CMSIS

OBJS = main.o kernel.o minidexed.o config.o mididevice.o midikeyboard.o serialmididevice.o pckeyboard.o perftimer.o \
       emulator/lcd.o emulator/mcu.o emulator/mcu_opcodes.o emulator/pcm.o

OPTIMIZE = -O3

include ./Rules.mk
